packages:
  - 'packages/*'
  - 'frontend'
  - 'site'
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  '@opentelemetry/exporter-metrics-otlp-http': ^0.222.0
  '@opentelemetry/exporter-trace-otlp-http': ^0.222.0
