package backend

import (
	"context"

	"github.com/sachncs/promptsheon/backend/models"
)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

// Webhook methods. All no-op on the api test mock.
func (m *mockRepo) SaveWebhookEndpoint(_ context.Context, _ *models.WebhookEndpointRecord) error {
	return nil
}
func (m *mockRepo) GetWebhookEndpoint(_ context.Context, _ string) (*models.WebhookEndpointRecord, error) {
	return &models.WebhookEndpointRecord{}, nil
}
func (m *mockRepo) DeleteWebhookEndpoint(_ context.Context, _ string) error { return nil }
func (m *mockRepo) ListWebhookEndpoints(_ context.Context) ([]*models.WebhookEndpointRecord, error) {
	return nil, nil
}
