package backend

import (
	"context"
	"database/sql"

	"github.com/sachncs/promptsheon/backend/errs"
	"github.com/sachncs/promptsheon/backend/models"
)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

func (m *mockRepo) CreateUser(_ context.Context, u *models.User) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.users[u.ID] = u
	return nil
}
func (m *mockRepo) BootstrapAdmin(_ context.Context, u *models.User, key *models.APIKey) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if len(m.users) > 0 {
		return errs.ErrStoreConflict
	}
	m.users[u.ID] = u
	m.apiKeys[key.ID] = key
	return nil
}
func (m *mockRepo) GetUser(_ context.Context, id string) (*models.User, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	u, ok := m.users[id]
	if !ok {
		return nil, sql.ErrNoRows
	}
	return u, nil
}
func (m *mockRepo) GetUserByEmail(_ context.Context, email string) (*models.User, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	for _, u := range m.users {
		if u.Email == email {
			return u, nil
		}
	}
	return nil, sql.ErrNoRows
}
func (m *mockRepo) ListUsers(_ context.Context) ([]*models.User, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	users := make([]*models.User, 0, len(m.users))
	for _, u := range m.users {
		users = append(users, u)
	}
	return users, nil
}
func (m *mockRepo) UpdateUser(_ context.Context, u *models.User) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.users[u.ID] = u
	return nil
}
func (m *mockRepo) DeleteUser(_ context.Context, id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.users[id]; !ok {
		return sql.ErrNoRows
	}
	delete(m.users, id)
	return nil
}
