// M3.5 gRPC plugin transport — wire contract.
//
// Service shape: each plugin binary is a gRPC server; the
// supervisor is a gRPC client. The wire format is the canonical
// contract; v0.1.x plugin binaries can implement either the
// net/rpc PluginRPC (subprocess.go) or this gRPC pluginv1.PluginServer.
//
// F-23 forward-only. The net/rpc implementation in
// internal/subprocess remains the production transport for
// v0.1.x; the gRPC adapter replaces it in M3.5. The two
// transports share the same wire semantics (Ping/Health/Stop)
// so plugins written against one can be ported to the other.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: internal/pluginproto/proto/plugin.proto

package pluginv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_pluginproto_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the manifest entry name the plugin was
	// registered under.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version is the plugin binary's semver string.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_pluginproto_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_pluginproto_proto_plugin_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OK is true when the plugin is ready to accept traffic.
	// A nil err in the unary response is the canonical "OK";
	// this field is reserved for future structured health
	// reports.
	Ok            bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_pluginproto_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_internal_pluginproto_proto_plugin_proto_rawDescGZIP(), []int{4}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pluginproto_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_internal_pluginproto_proto_plugin_proto_rawDescGZIP(), []int{5}
}

var File_internal_pluginproto_proto_plugin_proto protoreflect.FileDescriptor

const file_internal_pluginproto_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"'internal/pluginproto/proto/plugin.proto\x12\x0fpluginv1.v0_1_0\"\r\n" +
	"\vPingRequest\"<\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x0f\n" +
	"\rHealthRequest\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse2\xdd\x01\n" +
	"\x06Plugin\x12C\n" +
	"\x04Ping\x12\x1c.pluginv1.v0_1_0.PingRequest\x1a\x1d.pluginv1.v0_1_0.PingResponse\x12I\n" +
	"\x06Health\x12\x1e.pluginv1.v0_1_0.HealthRequest\x1a\x1f.pluginv1.v0_1_0.HealthResponse\x12C\n" +
	"\x04Stop\x12\x1c.pluginv1.v0_1_0.StopRequest\x1a\x1d.pluginv1.v0_1_0.StopResponseBGZEgithub.com/sachncs/promptsheon/internal/pluginproto/pluginv1;pluginv1b\x06proto3"

var (
	file_internal_pluginproto_proto_plugin_proto_rawDescOnce sync.Once
	file_internal_pluginproto_proto_plugin_proto_rawDescData []byte
)

func file_internal_pluginproto_proto_plugin_proto_rawDescGZIP() []byte {
	file_internal_pluginproto_proto_plugin_proto_rawDescOnce.Do(func() {
		file_internal_pluginproto_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pluginproto_proto_plugin_proto_rawDesc), len(file_internal_pluginproto_proto_plugin_proto_rawDesc)))
	})
	return file_internal_pluginproto_proto_plugin_proto_rawDescData
}

var file_internal_pluginproto_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_pluginproto_proto_plugin_proto_goTypes = []any{
	(*PingRequest)(nil),    // 0: pluginv1.v0_1_0.PingRequest
	(*PingResponse)(nil),   // 1: pluginv1.v0_1_0.PingResponse
	(*HealthRequest)(nil),  // 2: pluginv1.v0_1_0.HealthRequest
	(*HealthResponse)(nil), // 3: pluginv1.v0_1_0.HealthResponse
	(*StopRequest)(nil),    // 4: pluginv1.v0_1_0.StopRequest
	(*StopResponse)(nil),   // 5: pluginv1.v0_1_0.StopResponse
}
var file_internal_pluginproto_proto_plugin_proto_depIdxs = []int32{
	0, // 0: pluginv1.v0_1_0.Plugin.Ping:input_type -> pluginv1.v0_1_0.PingRequest
	2, // 1: pluginv1.v0_1_0.Plugin.Health:input_type -> pluginv1.v0_1_0.HealthRequest
	4, // 2: pluginv1.v0_1_0.Plugin.Stop:input_type -> pluginv1.v0_1_0.StopRequest
	1, // 3: pluginv1.v0_1_0.Plugin.Ping:output_type -> pluginv1.v0_1_0.PingResponse
	3, // 4: pluginv1.v0_1_0.Plugin.Health:output_type -> pluginv1.v0_1_0.HealthResponse
	5, // 5: pluginv1.v0_1_0.Plugin.Stop:output_type -> pluginv1.v0_1_0.StopResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pluginproto_proto_plugin_proto_init() }
func file_internal_pluginproto_proto_plugin_proto_init() {
	if File_internal_pluginproto_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pluginproto_proto_plugin_proto_rawDesc), len(file_internal_pluginproto_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pluginproto_proto_plugin_proto_goTypes,
		DependencyIndexes: file_internal_pluginproto_proto_plugin_proto_depIdxs,
		MessageInfos:      file_internal_pluginproto_proto_plugin_proto_msgTypes,
	}.Build()
	File_internal_pluginproto_proto_plugin_proto = out.File
	file_internal_pluginproto_proto_plugin_proto_goTypes = nil
	file_internal_pluginproto_proto_plugin_proto_depIdxs = nil
}
