export const ENVIRONMENTS = ['dev', 'staging', 'prod'] as const;
export const RELEASE_STATUSES = ['pending', 'active', 'superseded', 'rejected'] as const;
export const USER_ROLES = ['admin', 'editor', 'reader', 'system'] as const;
export const EVAL_RUN_STATUSES = ['running', 'passed', 'failed', 'error'] as const;
export const ALERT_SEVERITIES = ['info', 'warning', 'critical'] as const;
export const ALERT_STATUSES = ['active', 'resolved'] as const;
export const SELF_EVOLVE_STATUSES = ['idle', 'detected', 'revising', 'validating', 'promoted', 'rejected'] as const;
export const LINEAGE_SOURCES = ['recommendation', 'manual', 'migration'] as const;
export const ENFORCER_KINDS = ['budget', 'quota'] as const;

export const MAX_PAGE_SIZE = 100;
export const DEFAULT_PAGE_SIZE = 20;
export const SYSTEM_USER_ID = 'api';
export const SYSTEM_USER_EMAIL = 'system@promptsheon.internal';
export const CAS_OBJECT_DIR_DEPTH = 2;
export const CAS_HASH_LENGTH = 64;
export const API_KEY_PREFIX = 'psk_';
export const DEFAULT_PORT = 8080;
export const DEFAULT_HOST = '127.0.0.1';
