//go:build tests_migration


package promptsheon

import (
	"github.com/sachncs/promptsheon/promptsheon/capability"
		"context"
	"database/sql"
	"fmt"

	"github.com/sachncs/promptsheon/promptsheon/errs"
)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

func (m *mockRepo) CreateWorkspace(_ context.Context, w *capability.Workspace) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.workspaces[w.ID] = w
	return nil
}
func (m *mockRepo) GetWorkspace(_ context.Context, id string) (*capability.Workspace, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	w, ok := m.workspaces[id]
	if !ok {
		return nil, sql.ErrNoRows
	}
	return w, nil
}
func (m *mockRepo) ListWorkspaces(_ context.Context) ([]*capability.Workspace, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	ws := make([]*capability.Workspace, 0, len(m.workspaces))
	for _, w := range m.workspaces {
		ws = append(ws, w)
	}
	return ws, nil
}
func (m *mockRepo) UpdateWorkspace(_ context.Context, w *capability.Workspace) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.workspaces[w.ID] = w
	return nil
}
func (m *mockRepo) DeleteWorkspace(_ context.Context, id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.workspaces[id]; !ok {
		return sql.ErrNoRows
	}
	delete(m.workspaces, id)
	return nil
}
func (m *mockRepo) CreateProject(_ context.Context, p *capability.Project) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.projects[p.ID] = p
	return nil
}
func (m *mockRepo) GetProject(_ context.Context, id string) (*capability.Project, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	p, ok := m.projects[id]
	if !ok {
		return nil, sql.ErrNoRows
	}
	return p, nil
}
func (m *mockRepo) ListProjects(_ context.Context, workspaceID string) ([]*capability.Project, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var projs []*capability.Project
	for _, p := range m.projects {
		if p.WorkspaceID == workspaceID {
			projs = append(projs, p)
		}
	}
	return projs, nil
}
func (m *mockRepo) UpdateProject(_ context.Context, p *capability.Project) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.projects[p.ID] = p
	return nil
}
func (m *mockRepo) DeleteProject(_ context.Context, id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.projects[id]; !ok {
		return sql.ErrNoRows
	}
	delete(m.projects, id)
	return nil
}
func (m *mockRepo) CreateCapability(_ context.Context, c *capability.Capability) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.capabilities[c.ID] = c
	return nil
}
func (m *mockRepo) GetCapability(_ context.Context, id string) (*capability.Capability, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	c, ok := m.capabilities[id]
	if !ok {
		return nil, sql.ErrNoRows
	}
	return c, nil
}
func (m *mockRepo) ListCapabilities(_ context.Context, projectID string) ([]*capability.Capability, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var caps []*capability.Capability
	for _, c := range m.capabilities {
		if c.ProjectID == projectID {
			caps = append(caps, c)
		}
	}
	return caps, nil
}
func (m *mockRepo) UpdateCapability(_ context.Context, c *capability.Capability) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.capabilities[c.ID] = c
	return nil
}
func (m *mockRepo) UpdateSelfEvolveConfig(_ context.Context, id string, cfg capability.SelfEvolveConfig) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	c, ok := m.capabilities[id]
	if !ok {
		return errs.ErrStoreNotFound
	}
	c.SelfEvolve = cfg
	m.capabilities[id] = c
	return nil
}
func (m *mockRepo) DeleteCapability(_ context.Context, id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.capabilities[id]; !ok {
		return sql.ErrNoRows
	}
	delete(m.capabilities, id)
	return nil
}
func (m *mockRepo) CreateVersion(_ context.Context, v *capability.Version) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.versions[v.ID] = v
	m.versionsByCap[v.CapabilityID] = append(m.versionsByCap[v.CapabilityID], v)
	return nil
}
func (m *mockRepo) GetVersion(_ context.Context, id string) (*capability.Version, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok := m.versions[id]
	if !ok {
		return nil, sql.ErrNoRows
	}
	return v, nil
}
func (m *mockRepo) ListVersions(_ context.Context, capabilityID string) ([]*capability.Version, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.versionsByCap[capabilityID], nil
}
func (m *mockRepo) GetVersionByNumber(_ context.Context, capabilityID string, version int) (*capability.Version, error) {
	if v, ok := m.versions[fmt.Sprintf("%s_%d", capabilityID, version)]; ok {
		return v, nil
	}
	return nil, errs.ErrStoreNotFound
}

func (m *mockRepo) SetCapabilityContract(_ context.Context, capabilityID string, c *capability.CapabilityContract) error {
	if c == nil {
		delete(m.contracts, capabilityID)
		return nil
	}
	m.contracts[capabilityID] = c
	return nil
}

func (m *mockRepo) GetCapabilityContract(_ context.Context, capabilityID string) (*capability.CapabilityContract, error) {
	if c, ok := m.contracts[capabilityID]; ok {
		return c, nil
	}
	return nil, errs.ErrStoreNotFound
}

func (m *mockRepo) GetCapabilityReputation(_ context.Context, capabilityID string) (capability.Reputation, error) {
	return capability.Reputation{CapabilityID: capabilityID, TrustScore: 0.5, EvalPassRate: 0.5, SLOAdherenceRate: 0.5, DecisionAdoptionRate: 0.5, SampleSize: 1}, nil
}

func (m *mockRepo) CatalogSearch(_ context.Context, _ string, query string, _ int) ([]*capability.Capability, error) {
	if query == "" {
		return nil, nil
	}
	return []*capability.Capability{{ID: "c1", Name: "matching"}}, nil
}

func (m *mockRepo) GetLatestVersion(_ context.Context, capabilityID string) (*capability.Version, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	versions := m.versionsByCap[capabilityID]
	if len(versions) == 0 {
		return nil, errs.ErrStoreNotFound
	}
	latest := versions[0]
	for _, v := range versions[1:] {
		if v.Version > latest.Version {
			latest = v
		}
	}
	return latest, nil
}

func (m *mockRepo) CreateExecution(_ context.Context, e *capability.Execution) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.executions[e.ID] = e
	return nil
}
func (m *mockRepo) GetExecution(_ context.Context, id string) (*capability.Execution, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	e, ok := m.executions[id]
	if !ok {
		return nil, sql.ErrNoRows
	}
	return e, nil
}
func (m *mockRepo) ListExecutions(_ context.Context, filter capability.ExecutionFilter) ([]*capability.Execution, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var execs []*capability.Execution
	for _, e := range m.executions {
		if e.CapabilityVersionID == filter.CapabilityVersionID {
			execs = append(execs, e)
		}
	}
	return execs, nil
}
