//go:build tests_migration


package promptsheon

import (
	"github.com/sachncs/promptsheon/promptsheon/models"
		"context"

)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

// Vault state methods. Returns nil for all reads; writes no-op.
// The api tests don't exercise vault state directly; the vault
// package has its own tests.
func (m *mockRepo) GetVaultState(_ context.Context) (*models.VaultState, error) {
	return nil, nil
}
func (m *mockRepo) SaveVaultState(_ context.Context, _ *models.VaultState) error {
	return nil
}
