package promptsheon

import "context"

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

// Workspace state methods. Returns 0/empty; writes no-op.
func (m *mockRepo) GetWSNextID(_ context.Context) (int64, error) {
	return 0, nil
}
func (m *mockRepo) SetWSNextID(_ context.Context, _ int64) error { return nil }
