package promptsheon

import (
	"context"

	"github.com/sachncs/promptsheon/promptsheon/harness"
	"github.com/sachncs/promptsheon/promptsheon/models"
)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

// Alerting methods.
func (m *mockRepo) SaveAlertRule(_ context.Context, _ *models.AlertRuleRecord) error { return nil }
func (m *mockRepo) GetAlertRule(_ context.Context, _ string) (*models.AlertRuleRecord, error) {
	return &models.AlertRuleRecord{}, nil
}
func (m *mockRepo) DeleteAlertRule(_ context.Context, _ string) error { return nil }
func (m *mockRepo) ListAlertRules(_ context.Context) ([]*models.AlertRuleRecord, error) {
	return nil, nil
}
func (m *mockRepo) SaveAlert(_ context.Context, _ *models.AlertRecord) error { return nil }
func (m *mockRepo) GetAlert(_ context.Context, _ string) (*models.AlertRecord, error) {
	return &models.AlertRecord{}, nil
}
func (m *mockRepo) UpdateAlert(_ context.Context, _ *models.AlertRecord) error { return nil }
func (m *mockRepo) ListAlerts(_ context.Context, _ string) ([]*models.AlertRecord, error) {
	return nil, nil
}
func (m *mockRepo) SaveNotificationGroup(_ context.Context, _ *models.NotificationGroupRecord) error {
	return nil
}
func (m *mockRepo) GetNotificationGroup(_ context.Context, _ string) (*models.NotificationGroupRecord, error) {
	return &models.NotificationGroupRecord{}, nil
}
func (m *mockRepo) DeleteNotificationGroup(_ context.Context, _ string) error { return nil }
func (m *mockRepo) ListNotificationGroups(_ context.Context) ([]*models.NotificationGroupRecord, error) {
	return nil, nil
}

// GetChannelsForAlertRule is a no-op on the api test mock:
// alert routing is exercised through real alerting tests, not
// through the api surface.
func (m *mockRepo) GetChannelsForAlertRule(_ context.Context, _ string) ([]string, error) {
	return nil, nil
}

func (m *mockRepo) LinkRuleToGroup(_ context.Context, _, _ string) error     { return nil }
func (m *mockRepo) UnlinkRuleFromGroup(_ context.Context, _, _ string) error { return nil }

// ListEvalResultsForRun is used by release.NewService to back the
// rolling-average scoring; the api tests don't exercise that path
// but the interface contract requires the method.
func (m *mockRepo) ListEvalResultsForRun(_ context.Context, runID string) ([]harness.EvalResult, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var out []harness.EvalResult
	for _, r := range m.evalResults {
		if r.RunID == runID {
			out = append(out, r)
		}
	}
	return out, nil
}
