
package promptsheon

import (
		"context"

	"github.com/sachncs/promptsheon/promptsheon/errs"

	"github.com/sachncs/promptsheon/promptsheon/approval")

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

func (m *mockRepo) CreateApproval(_ context.Context, a *approval.Approval) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	cp := *a
	m.approvals[a.ReleaseID] = &cp
	return nil
}
func (m *mockRepo) GetApproval(_ context.Context, releaseID string) (*approval.Approval, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	a, ok := m.approvals[releaseID]
	if !ok {
		return nil, errs.ErrApprovalNotFound
	}
	cp := *a
	return &cp, nil
}
func (m *mockRepo) UpdateApproval(_ context.Context, a *approval.Approval) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.approvals[a.ReleaseID]; !ok {
		return errs.ErrApprovalNotFound
	}
	cp := *a
	m.approvals[a.ReleaseID] = &cp
	return nil
}
func (m *mockRepo) DeleteApproval(_ context.Context, releaseID string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.approvals, releaseID)
	return nil
}
