package promptsheon

import (
	"context"
	"database/sql"

	"github.com/sachncs/promptsheon/promptsheon/models"
)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

func (m *mockRepo) CreateAPIKey(_ context.Context, key *models.APIKey) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.apiKeys[key.ID] = key
	m.apiKeysByHash[key.KeyHash] = key
	return nil
}
func (m *mockRepo) GetAPIKeyByHash(_ context.Context, keyHash string) (*models.APIKey, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	key, ok := m.apiKeysByHash[keyHash]
	if !ok {
		return nil, nil
	}
	return key, nil
}
func (m *mockRepo) GetAPIKeyByID(_ context.Context, id string) (*models.APIKey, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	key, ok := m.apiKeys[id]
	if !ok {
		return nil, sql.ErrNoRows
	}
	return key, nil
}
func (m *mockRepo) DeleteAPIKey(_ context.Context, id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.apiKeys, id)
	for k, v := range m.apiKeysByHash {
		if v.ID == id {
			delete(m.apiKeysByHash, k)
			break
		}
	}
	return nil
}
func (m *mockRepo) ListAPIKeysByUser(_ context.Context, userID string) ([]*models.APIKey, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var keys []*models.APIKey
	for _, k := range m.apiKeys {
		if k.UserID == userID {
			keys = append(keys, k)
		}
	}
	return keys, nil
}
func (m *mockRepo) UpdateAPIKeyLastUsed(_ context.Context, _ string) error { return nil }
