package promptsheon

import (
	"github.com/sachncs/promptsheon/promptsheon/models"
		"context"
	"database/sql"

)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

func (m *mockRepo) SaveProviderKey(_ context.Context, pk *models.ProviderKey) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.providerKeys[pk.ID] = pk
	return nil
}
func (m *mockRepo) GetProviderKey(_ context.Context, id string) (*models.ProviderKey, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	pk, ok := m.providerKeys[id]
	if !ok {
		return nil, sql.ErrNoRows
	}
	return pk, nil
}
func (m *mockRepo) GetProviderKeyByName(_ context.Context, providerName, keyName string) (*models.ProviderKey, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	for _, pk := range m.providerKeys {
		if pk.ProviderName == providerName && pk.KeyName == keyName {
			return pk, nil
		}
	}
	return nil, sql.ErrNoRows
}
func (m *mockRepo) DeleteProviderKey(_ context.Context, id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.providerKeys[id]; !ok {
		return sql.ErrNoRows
	}
	delete(m.providerKeys, id)
	return nil
}
func (m *mockRepo) ListProviderKeys(_ context.Context) ([]*models.ProviderKey, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	keys := make([]*models.ProviderKey, 0, len(m.providerKeys))
	for _, k := range m.providerKeys {
		keys = append(keys, k)
	}
	return keys, nil
}
