package promptsheon

import (
	"github.com/sachncs/promptsheon/promptsheon/settings"
		"context"
	"database/sql"

)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

func (m *mockRepo) GetSystemConfig(_ context.Context, _ string) (settings.CRDTRecord, error) {
	return settings.CRDTRecord{}, sql.ErrNoRows
}
func (m *mockRepo) SetSystemConfig(_ context.Context, _ settings.CRDTRecord) error {
	return nil
}
func (m *mockRepo) ListSystemConfig(_ context.Context) ([]settings.CRDTRecord, error) {
	return nil, nil
}
func (m *mockRepo) MergeSystemConfig(_ context.Context, _ string, _ []settings.CRDTRecord) error {
	return nil
}
