
package promptsheon

import (
	"github.com/sachncs/promptsheon/promptsheon/harness"
		"context"

	"github.com/sachncs/promptsheon/promptsheon/errs"
)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

func (m *mockRepo) CreatePrecondition(_ context.Context, p *harness.Precondition) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	cp := *p
	m.preconditions[p.ID] = &cp
	return nil
}
func (m *mockRepo) ListPreconditionsForCapability(_ context.Context, capabilityID string) ([]*harness.Precondition, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var out []*harness.Precondition
	for _, p := range m.preconditions {
		if p.CapabilityID == capabilityID {
			cp := *p
			out = append(out, &cp)
		}
	}
	return out, nil
}
func (m *mockRepo) GetPrecondition(_ context.Context, id string) (*harness.Precondition, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	p, ok := m.preconditions[id]
	if !ok {
		return nil, errs.ErrStoreNotFound
	}
	cp := *p
	return &cp, nil
}
func (m *mockRepo) UpdatePrecondition(_ context.Context, p *harness.Precondition) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.preconditions[p.ID]; !ok {
		return errs.ErrStoreNotFound
	}
	cp := *p
	m.preconditions[p.ID] = &cp
	return nil
}
func (m *mockRepo) DeletePrecondition(_ context.Context, id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.preconditions, id)
	return nil
}
