package promptsheon

import (
	"github.com/sachncs/promptsheon/promptsheon/store"
	"github.com/sachncs/promptsheon/promptsheon/models"
	"context"

)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

func (m *mockRepo) AppendAudit(_ context.Context, entry *models.AuditEntry) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.auditEntries = append(m.auditEntries, entry)
	return nil
}
func (m *mockRepo) ListAudit(_ context.Context, _ *models.AuditFilter) ([]*models.AuditEntry, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.auditEntries, nil
}
func (m *mockRepo) ExportAudit(_ context.Context, _ *models.AuditFilter) ([]*models.AuditEntry, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.auditEntries, nil
}
func (m *mockRepo) VerifyAuditChain(_ context.Context) (*store.AuditVerifyResult, error) {
	return &store.AuditVerifyResult{Ok: true}, nil
}
