
package promptsheon

import (
	"github.com/sachncs/promptsheon/promptsheon/release"
		"context"

	"github.com/sachncs/promptsheon/promptsheon/errs"
)

// Code generated by tools/refactor-mockstore. DO NOT EDIT.

func (m *mockRepo) CreateRelease(_ context.Context, r *release.Release) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	cp := *r
	m.releases[r.ID] = &cp
	m.releasesByCap[r.CapabilityID] = append(m.releasesByCap[r.CapabilityID], &cp)
	return nil
}
func (m *mockRepo) GetRelease(_ context.Context, id string) (*release.Release, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	r, ok := m.releases[id]
	if !ok {
		return nil, errs.ErrReleaseNotFound
	}
	cp := *r
	return &cp, nil
}
func (m *mockRepo) ListReleasesForCapability(_ context.Context, capabilityID string) ([]*release.Release, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	out := make([]*release.Release, 0, len(m.releasesByCap[capabilityID]))
	for _, r := range m.releasesByCap[capabilityID] {
		cp := *r
		out = append(out, &cp)
	}
	return out, nil
}
func (m *mockRepo) ListActiveReleasesForEnvironment(_ context.Context, env release.Environment) ([]*release.Release, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	var out []*release.Release
	for _, r := range m.releases {
		if r.Environment == env && r.Status == release.StatusActive {
			cp := *r
			out = append(out, &cp)
		}
	}
	return out, nil
}
func (m *mockRepo) UpdateRelease(_ context.Context, r *release.Release) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.releases[r.ID]; !ok {
		return errs.ErrReleaseNotFound
	}
	cp := *r
	m.releases[r.ID] = &cp
	for i, existing := range m.releasesByCap[r.CapabilityID] {
		if existing.ID == r.ID {
			m.releasesByCap[r.CapabilityID][i] = &cp
			break
		}
	}
	return nil
}
func (m *mockRepo) DeleteRelease(_ context.Context, id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.releases, id)
	return nil
}
func (m *mockRepo) ActivateAtomic(_ context.Context, prior, next *release.Release) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if prior != nil {
		if _, ok := m.releases[prior.ID]; !ok {
			return errs.ErrReleaseNotFound
		}
		cp := *prior
		m.releases[prior.ID] = &cp
	}
	if _, ok := m.releases[next.ID]; !ok {
		return errs.ErrReleaseNotFound
	}
	cp := *next
	m.releases[next.ID] = &cp
	return nil
}
