// Package recommendation aggregates the Recommendation and Decision
// types that close the loop from production Execution back to the
// next Capability Version.
//
// A Recommendation is an advisory proposal generated by the optimizer
// in response to Observations. A Decision is the recorded outcome of
// that proposal: who decided, when, and why.
//
// The Decision is what turns advisory output into a state change. We
// keep Recommendation and Decision in the same package because their
// lifecycles are tightly coupled — every Recommendation that is acted
// upon produces a Decision — but they remain distinct value types so
// "rejected" Recommendations are preserved for audit, not deleted.
package recommendation

import (
	"errors"
	"fmt"
	"time"

	"github.com/sachncs/promptsheon/internal/capability"
)

// Outcome is the disposition of a Recommendation.
type Outcome string

const (
	// OutcomePending means the Recommendation has been emitted but
	// no Decision is recorded yet.
	OutcomePending Outcome = "pending"
	// OutcomeAdopted means the Recommendation was acted upon and a
	// new Capability Version has been created.
	OutcomeAdopted Outcome = "adopted"
	// OutcomeRejected means a decision-maker explicitly declined.
	// Rejection is recorded with a reason and never silently
	// discarded.
	OutcomeRejected Outcome = "rejected"
	// OutcomeSuperseded means the Recommendation became moot
	// because a different Version was created for an unrelated
	// reason (for example, an engineer shipped a manual change).
	OutcomeSuperseded Outcome = "superseded"
)

// Decision records the outcome of one Recommendation.
//
// Decisions are immutable. A Recommendation's history is reconstructed
// by replaying Decisions against its ID.
type Decision struct {
	ID               string    `json:"id"`
	RecommendationID string    `json:"recommendation_id"`
	Outcome          Outcome   `json:"outcome"`
	DecidedBy        string    `json:"decided_by"`
	DecidedAt        time.Time `json:"decided_at"`
	Reason           string    `json:"reason,omitempty"`
	ResultingVersion int       `json:"resulting_version,omitempty"`
	Auto             bool      `json:"auto"`
}

// ErrUnknownOutcome is returned when an outcome value is not in the
// closed set.
var ErrUnknownOutcome = errors.New("decision: unknown outcome")

// NewAdopted constructs an Adopted Decision for an adopter that is
// not the auto-promotion path. Use NewAdoptedAuto for the
// auto-promotion case so that auto vs human adoption is captured
// explicitly in the audit log.
func NewAdopted(recommendationID, decidedBy, reason string, resultingVersion int) (Decision, error) {
	return newDecision(recommendationID, OutcomeAdopted, decidedBy, reason, resultingVersion, false)
}

// NewRejected constructs a Rejected Decision.
func NewRejected(recommendationID, decidedBy, reason string) (Decision, error) {
	return newDecision(recommendationID, OutcomeRejected, decidedBy, reason, 0, false)
}

// NewAdoptedAuto constructs an Adopted Decision for the
// auto-promotion path. The Auto flag distinguishes this from human
// adoption in audit reports.
func NewAdoptedAuto(recommendationID string, resultingVersion int) (Decision, error) {
	return newDecision(recommendationID, OutcomeAdopted, "system:auto-optimizer", "auto-promotion", resultingVersion, true)
}

// NewSuperseded marks the Recommendation as moot. It is recorded
// without an adopter identity because the reason for supersession is
// an internal event.
func NewSuperseded(recommendationID string) (Decision, error) {
	return newDecision(recommendationID, OutcomeSuperseded, "system:scheduler", "", 0, true)
}

func newDecision(recommendationID string, outcome Outcome, decidedBy, reason string, resultingVersion int, auto bool) (Decision, error) {
	if recommendationID == "" {
		return Decision{}, errors.New("decision: recommendation_id is required")
	}
	if !auto && decidedBy == "" {
		return Decision{}, errors.New("decision: decided_by is required for human decisions")
	}
	switch outcome {
	case OutcomeAdopted, OutcomeRejected, OutcomeSuperseded:
	default:
		return Decision{}, fmt.Errorf("%w: %q", ErrUnknownOutcome, outcome)
	}
	if outcome == OutcomeAdopted && resultingVersion <= 0 {
		return Decision{}, errors.New("decision: adopted requires positive resulting_version")
	}
	if outcome != OutcomeAdopted && resultingVersion != 0 {
		return Decision{}, errors.New("decision: resulting_version only valid for adopted")
	}
	return Decision{
		ID:               recommendationID + ":" + string(outcome),
		RecommendationID: recommendationID,
		Outcome:          outcome,
		DecidedBy:        decidedBy,
		DecidedAt:        time.Now().UTC(),
		Reason:           reason,
		ResultingVersion: resultingVersion,
		Auto:             auto,
	}, nil
}

// CanAutoAdopt reports whether the Recommendation's type and
// confidence are eligible for auto-promotion.
//
// The threshold is intentionally conservative: a Recommendation
// must be flagged AutoApplicable by the Recommendation itself, must
// have confidence above the supplied threshold, and must be of a
// low-blast-radius type. Switching models is high blast radius;
// compressing prompts is low blast radius. The threshold and the
// set of low-blast-radius types are policy decisions; this function
// only encodes the conservative default.
//
// The decision to actually auto-promote lives in the optimizer
// package, where the workspace's auto-promotion policy is consulted.
// This function exists here so the same conservative checks are
// reusable from any caller (for example, a CI gate that wants to know
// whether a recommendation is even theoretically eligible).
func CanAutoAdopt(r capability.Recommendation, minConfidence float64) bool {
	if !r.AutoApplicable {
		return false
	}
	if r.Confidence < minConfidence {
		return false
	}
	switch r.Type {
	case capability.RecommendationCompressPrompt,
		capability.RecommendationEnableCache,
		capability.RecommendationDisableReasoning,
		capability.RecommendationRemoveTool:
		return true
	default:
		return false
	}
}
